# Generated by Django 4.2.1 on 2023-10-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_logupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logupload',
            name='uploadedFile',
        ),
        migrations.AddField(
            model_name='logupload',
            name='uploadedFile_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
