# Generated by Django 4.2.1 on 2023-10-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0006_forwarderdata_new_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forwarderdata',
            name='new_data',
        ),
    ]
